project:
  type: book
  output-dir: docs
  resources: syllabus.pdf
  pre-render: _render_syllabus.r


title-block-author-single: "Instructor"
title-block-published: ""

book:
  # sidebar:
  #   tools:
  #     - icon: file-pdf
  #       menu:
  #         - text: Download PDF syllabus
  #           url:  psyc-bc2124-syllabus-fall23.pdf
  title: "Personality Psychology Lab Handbook"
  subtitle: |
    | Barnard College
    | Department of Psychology
    | PSYC BC2124
  date: "1/31/2023"
  date-format: "[Fall 2023]"
  output-file: Personality-Psychology-Lab-Handbook

  chapters:
    - index.qmd
    - part: "Project 1: $t$-test"
      chapters:
        - lab-2.qmd
        - lab-3.qmd
        - lab-4.qmd
        - lab-5.qmd
    - part: "Project 2: Correlation"
      chapters:
        - lab-6.qmd
        - lab-7.qmd
        - lab-8.qmd
        - lab-9.qmd
    - part: "Project 3: Regression"
      chapters:
        - lab-10.qmd
        - lab-11.qmd
        - lab-12.qmd
        - lab-13.qmd
  appendices:
    - appendix-r-basics.qmd
    - appendix-correlation.qmd
    - appendix-regression.qmd
    - appendix-rubric.qmd
  # downloads: pdf
  # sidebar:
  #   tools:
  #     - icon: github
  #       href: https://github.com/robbrotherton/bc2137/

toc-depth: 3
number-depth: 0
number-sections: false

# comments:
#     hypothesis:
#       theme: clean
#       openSidebar: false

crossref:
  appendix-title: Appendix

format:
  html:
    theme:
      light: [flatly, custom.scss]
      dark:  [darkly, custom.scss]
    link-external-newwindow: true
  # pdf: default

