project:
  type: book
  output-dir: docs
  resources: syllabus.pdf
  pre-render: _render_syllabus.r


title-block-author-single: "Instructor"
title-block-published: ""

book:
  # sidebar:
  #   tools:
  #     - icon: file-pdf
  #       menu:
  #         - text: Download PDF syllabus
  #           url:  psyc-bc2124-syllabus-fall23.pdf
  title: "Personality Psychology Lab Handbook"
  subtitle: |
    | Barnard College
    | Department of Psychology
    | PSYC BC2124
  date: "1/31/2023"
  date-format: "[Fall 2024]"
  output-file: Personality-Psychology-Lab-Handbook

  chapters:
    - index.qmd
    - part: "Project 1: $t$-test"
      chapters:
        - t-test_1_zodiac.qmd
        - t-test_2_zodiac.qmd
        - t-test_3_zodiac.qmd
        - t-test_4_zodiac.qmd
    - part: "Project 2: Correlation"
      chapters:
        - correlation_1_anes.qmd
        - correlation_2_anes.qmd
        - correlation_3_anes.qmd
        - correlation_4_anes.qmd
    - part: "Project 3: Regression"
      chapters:
        - regression_1_anes.qmd
        - regression_2_anes.qmd
        - regression_3_anes.qmd
        - regression_4_anes.qmd
  appendices:
    - appendix-r-basics.qmd
    - appendix-t-test.qmd
    - appendix-correlation.qmd
    - appendix-regression.qmd
    - appendix-rubric.qmd
  # downloads: pdf
  # sidebar:
  #   tools:
  #     - icon: github
  #       href: https://github.com/robbrotherton/bc2137/

toc-depth: 3
number-depth: 0
number-sections: false

# comments:
#     hypothesis:
#       theme: clean
#       openSidebar: false

crossref:
  appendix-title: Appendix

format:
  html:
    number-sections: true
    number-depth: 2
    number-offset: 1
    theme:
      light: [flatly, custom.scss]
      dark:  [darkly, custom.scss]
    link-external-newwindow: true
  # pdf: default

