project:
  type: book
  output-dir: docs

title-block-author-single: "Instructor"
title-block-published: ""

book:
  sidebar:
    tools:
      - icon: file-pdf
        menu:
          - text: PDF syllabus
            url:  psyc-bc2124-syllabus-fall23.pdf
  title: "Personality Psychology Lab Handbook"
  subtitle: |
    | Barnard College
    | Department of Psychology
    | PSYC BC2124
  date: "1/31/2023"
  date-format: "[Fall 2023]"
  output-file: "Personality-Psychology-Lab-Handbook-Fall-2023.pdf"

  chapters:
    - index.qmd
    - part: "Project 1: Correlation"
      chapters:
        - lab-2.qmd
        - lab-3.qmd
        - lab-4.qmd
        - lab-5.qmd
    - part: "Project 2: Multiple Regression"
      chapters:
        - lab-6.qmd
        - lab-7.qmd
        - lab-8.qmd
        - lab-9.qmd
    - part: "Project 3: Scale design"
      chapters:
        - lab-10.qmd
        - lab-11.qmd
        - lab-12.qmd
        - lab-13.qmd
  appendices:
    - appendix-r-basics.qmd
    # - a-statistics.qmd
    # - a-consent-form.qmd
    # - a-debrief.qmd
    # - a-writing-a-report.qmd
  # downloads: pdf
  # sidebar:
  #   tools:
  #     - icon: github
  #       href: https://github.com/robbrotherton/bc2137/

toc-depth: 3
number-depth: 0
number-sections: false

# comments:
#     hypothesis:
#       theme: clean
#       openSidebar: false

crossref:
  appendix-title: Appendix

format:
  pdf: default
  html:
    theme:
      light: [flatly, custom.scss]
      dark:  [darkly, custom.scss]
    link-external-newwindow: true

