---
title: Syllabus
number-sections: false
---

> Human personalities are rather like fractals. It is not just that what we do in the large-scale narratives of our lives—love, career, friendships—tends to be somewhat consistent over time, with us often repeating the same kinds of triumph or mistakes. Rather, what we do in tiny interactions like the way we shop, dress or talk to a stranger on a train or decorate our houses, shows the same kinds of patterns as can be observed from examining a whole life.
>
> -- <cite>Daniel Nettle, [Personality: What Makes You the Way You Are](http://www.columbia.edu/cgi-bin/cul/resolve?clio14146523)</cite>


## Course details

{{< include _syllabus_body.qmd >}}


<style>

#title-block-header {
  text-align: center;
}

#title-block-header.quarto-title-block.default .quarto-title-meta {
  display: unset;
}

</style>

<script>
function function1() {
  var toc = document.querySelector("#TOC");
  var link = document.createElement("a");
  link.innerHTML = "<i class='bi bi-file-pdf'></i> Download syllabus as PDF";
  toc.appendChild(link);
  link.href = "syllabus.pdf";
}

function1();
</script>
