# Lab 6: Project planning {.unnumbered}

In this lab, you will start your second project: conducting a multiple regression analysis using the same 2016 ANES data.

### Goals

- Understand the purpose of multiple regression
- Identify variables for your analysis
- Search the literature to find relevant research
- Formulate a brief research proposal


## Project overview

Multiple regression goes beyond simple correlations and captures the relationships between multiple __predictor__ variables and a single __outcome__ variable. It allows us to see the combined impact of multiple variables on one outcome, and how these predictors may interact with each other to affect the outcome. This can provide valuable insights into how the relationship between one predictor and the outcome might depend on another predictor.

For instance, researchers might examine how [one or more Big Five personality traits interact with age to predict job satisfaction](https://journals.sagepub.com/doi/pdf/10.1177/0306307016687990). Similarly, variables such as [income, education, and openness might be used in a multiple regression analysis to predict political ideology](https://www.annualreviews.org/doi/10.1146/annurev-polisci-051010-111659). Like with correlations, this doesn't mean that every extroverted, conscientious, and emotionally stable person will always be satisfied with their job, or that all educated, and open individuals are politically aligned in the same way. It's about general tendencies rather than strict rules. 

Like correlation, regression studies involve determining which psychological constructs to study, how to operationally define those constructs, and how to measure them. They then use these definitions and measurements to explore relationships, using appropriate statistical analyses.

With this project, you will dive deeper into the interplay between personality traits and other constructs, using multiple regression analysis to explore how a combination of predictors contributes to an outcome of your choice by analyzing existing data. This will empower you to better understand the complex interactions that shape human behavior and personality, beyond simple one-to-one relationships.


### Step 1. Choose your variables

We will again use data from the 2016 ANES survey. For regression, you can again think of your variables as predictors and outcome. You will still have a single outcome variable; however unlike the correlation analysis you did before, this time you will have more than one predictor. Again, the full dataset has more than 1,800 variables, so I'm going to constrain your choices; however, this time I'm giving you more freedom to choose.

Your __predictor__ variables will be any of the Big Five traits:

- Extraversion (V162333 & V162338)
- Agreeableness (V162334 & V162339)
- Conscientiousness (V162335 & V162340)
- Neuroticism (V162336 & V162341)
- Openness (V162337 & V162342)


Your __outcome__ variable will be any one of the feeling thermometer questions. Here are all the subjects of feeling thermometer variables you can choose from:

```{r}
#| echo: false
#| message: false

library(anesr)
library(tidyverse)
data("timeseries_2016_doc")

thermometers <- timeseries_2016_doc |> 
  # select(id, description) |> 
  filter(stringr::str_detect(tolower(description), "thermometer")) |> 
  select(description, id) |> 
  mutate(description = stringr::str_replace(description, regex(".*thermometer: ", ignore_case = TRUE), ""),
         description = stringr::str_to_title(description)) |> 
  mutate(li = glue::glue("<li>{description} ({toupper(id)})</li>")) |> 
  pull(li)


html_list <- paste0("<ul>", paste0(thermometers, collapse = ""), "</ul>")
```

`r html_list`



### Step 2. Find relevant research

As with Project 1, your approach and expectations should be informed by what has come before. Last time you didn't have so much choice of variables so I was able to point you to some relevant research. This time you have a wider choice so you'll have to find relevant research yourself about these (or related) personality traits.

#### What to look for

A published, scholarly journal article detailing an empirical finding relevant to your variables of interest. This might be a paper reporting one or several individual studies that the researchers conducted, or it may be a review paper or meta-analysis.^[A meta-analysis pools the findings of many individual studies by different researchers into a single analysis.]

#### Where to look

##### [Google Scholar](https://scholar.google.com)

Google Scholar searches the full text of scholarly articles. It casts a wide net, searching across all disciplines, and including books and other materials in addition to journal articles, so will likely find many articles not very relevant to the topic as well as those that are relevant.

##### [APA PsycINFO](http://www.columbia.edu/cgi-bin/cul/resolve?ALD2284)

The link above should take you to PsycINFO, a database for scholarly psychology research (you can also search for `psycinfo` in a CLIO quicksearch). PsycInfo gives you the ability to do more focused searching than Google Scholar.

-   You can add many keywords and combine them with the Boolean operators `AND`, `OR`, and `NOT` by selecting them from the dropdown boxes.
-   You can select where your keywords should appear, i.e. in the title, abstract, or full text of articles. Selecting `Word in Major Subject Heading` can help narrow down your search to articles that are actually on the topic you're interested in (rather than just containing the keyword).


### Step 3. Articulate your hypothesis

Having chosen your variables and found some relevant research to inform your theoretical perspective about how the variables are (or aren't) associated, you should be able to articulate your *hypothesis*. This is a formal statement of your expectations about how the variables are associated, and it will be tested quantitatively by computing the regression model.

The general hypothesis of a multiple regression is that there is a relationship between the predictor variables and the outcome variable; in other words, the predictors allow us to predict scores on the outcome more accurately than you would expect if the variables we unrelated.

A choice you will make at this point is whether you will study the simple additive effect of your predictors, or whether you will look at the __interaction__ between your predictors. An interaction effect means that two (or more) variables combined have a significantly larger effect on the outcome variable as compared to the sum of the individual variables alone. If you have two predictors, I would suggest looking at their interaction; if you want to include more than two predictors, just look at their additive effect.



## Your proposal

At the start of next week's class, each project team will give a short, informal presentation of their research proposal. This should outline:

-   Your variables of interest
-   Your theoretical perspective (based on the research you found)
-   Your expectations (this should follow from your theoretical perspective)
