# Lab 2: Project Planning {.unnumbered}

In this session we will begin the first project of the course: performing a correlational analysis using the ANES 2016 dataset. By the end of the session you will have a plan for your analysis.



## Goals


- Examine the ANES 2016 dataset
- Identify variables for your correlation analysis
- Search the literature to find relevant research
- Formulate a brief research proposal


# Project planning

A *correlation*  refers an association between two things. It is a statement of a *statistical* relationship--a general tendency, rather than a rigid law. To say that some aspect of personality is correlated with something else--for example, [neuroticism is correlated with lower wellbeing](https://psycnet.apa.org/fulltext/2020-03328-001.html) or [openness is correlated with greater cognitive ability](https://www.pnas.org/doi/10.1073/pnas.2212794120)--is to say that those things *tend* to go together. Not everyone who scores high on neuroticism will have lower wellbeing than anyone low on neuroticism, but there is some tendency for the two to go together on the whole.

Of course, these kind of correlations aren't just facts found lying around in nature; they are empirical findings produced by researchers. All the findings you learn about in the personality psychology lecture (and beyond) are the product of research procedures. Researchers decide what psychological constructs they want to investigate; how to operationally define those constructs; what statistical analyses are appropriate; and what conclusions may be drawn.

With this project, you will examine a correlation between a personality trait and some other construct of your choosing by analyzing existing data.


## Step 1. Examine the data

The dataset we will use is from the [American National Election Studies (ANES)](https://electionstudies.org/), academic surveys of voters in the United States conducted before and after every presidential election, going back to the 1940s. Specifically, for this project we will use data collected around the 2016 election. The reason for using this (instead of more recent data) is that the 2016 survey included a personality scale: the Ten-item Personality Inventory (TIPI: [Gosling et al., 2003](https://gosling.psy.utexas.edu/wp-content/uploads/2014/09/JRP-03-tipi.pdf)). This allow us to look at how the Big 5 personality traits of Openness, Conscientiousness, Extraversion, Agreeableness, and Neuroticism correlate with any of the other variables recorded in the survey.



## Step 2. Find relevant research

Real research doesn't happen in a vacuum; research plans and expectations should be informed by what has come before. Therefore once you have an idea of what variables you would like to analyze, you will search the literature to see what other researchers have found of these (or related) personality traits.

### Whatto look for

A published, scholarly journal article detailing an empirical finding relevant to your variables of interest. This might be a paper reporting one or several individual studies that the researchers conducted, or it may be a review or meta-analysis^[A meta-analysis pools the findings of many individual studies by different researchers into a single analysis.] paper.


### Where to look

#### [Google Scholar](https://scholar.google.com)

Google Scholar searches the full text of scholarly articles. It casts a wide net, searching across all disciplines, and including books and other materials in addition to journal articles, so will likely find many articles not very relevant to the topic as well as those that are relevant.


#### [APA PsycINFO](http://www.columbia.edu/cgi-bin/cul/resolve?ALD2284)

The link above should take you to PsycINFO, a database for scholarly psychology research (you can also serch for `psycinfo` in a CLIO quicksearch). PsycInfo gives you the ability to do much more focused searching than Google Scholar.

- You can do sequential searches and then combine them with the Boolean operators `AND`, `OR`, and `NOT` by selecting them from the dropdown boxes. 
- You can select where your keywords should appear, i.e. in the title, abstract, or full text of articles. Selecting `Word in Major Subject Heading` can help narrow down your search to articles that are actually on the topic you’re interested in (rather than just containing the keyword). 
- The *APA Thesaurus of Psychological Index Terms* link at the top can be useful for finding technical terms used in psychology, and other related ideas.





## Step 3. Articulate your hypothesis

Having chosen your variables and found some relevant research to inform your theoretical perspective about how the variables are (or aren't) associated, you should be able to articulate your *hypothesis*. This is a formal statement of your expectations about how the variables are associated, and it will be tested quantitatively by calculating a correlation statistic.




# Your proposal

At the start of next week's class, each project team will give a short, informal presentation of their research proposal. This should outline:

- Your variables of interest (one should be one of the Big 5, the other any variable of your choosing)
- Your theoretical perspective (based on the research you found)
- Your expectations (this should follow from your theoretical perspective)
